services:
  n8n:
    build: .
    container_name: n8n-tesseract
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_SECURE_COOKIE=false
      # Use your specific ngrok URL so n8n knows its public address
      - WEBHOOK_URL=https://amiably-vitiated-hilde.ngrok-free.dev
      # Allow Code node to import 'child_process' as a fallback for Tesseract
      - NODE_FUNCTION_ALLOW_BUILTIN=fs,child_process
      - NODE_FUNCTION_ALLOW_EXTERNAL=child_process,fs
    volumes:
      - n8n_data:/data
      - ./local_files:/files
    restart: always

volumes:
  n8n_data:
